### ISSUE TITLE
Add dummy course enrolment option

### ISSUE THREAD

**Issue by harunaka11037** [Peterburnett/QUTCapstone2020#8]
Create a dummy course enrolment option for this payment plugin.

**Comment by harunaka11037** [comment]
My current understanding of this issue is that to have a course enrolment option, an enrolment plugin must be created and added to moodle's `/enrol` folder.  If this is the only way of creating an enrolment method, either this plugin will have to be moved to `/enrol` to become an enrolment plugin, or a separate plugin will need developing.

**Comment by Peterburnett** [comment]
Hi all. You shouldnt need to use another plugin, you should just be able to resolve the conditions and say for sure, yes this user should be enrolled in this course. At that point, you can just process their enrolment using the manual enrolment method, using the functions from lib/enrollib.php such as this https://github.com/moodle/moodle/blob/master/lib/enrollib.php#L1124
